# Generated by Django 4.0.3 on 2022-03-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_users_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
