# Generated by Django 4.0.2 on 2022-03-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
