# Generated by Django 4.0.2 on 2022-03-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0005_contact_remove_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
