# Generated by Django 4.0.3 on 2022-04-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
