# Generated by Django 4.0.2 on 2022-04-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0016_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
