# Generated by Django 4.0.2 on 2022-04-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0018_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
