# Generated by Django 4.0.4 on 2022-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0020_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo6.png', upload_to='Profile Pic'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
