# Generated by Django 4.0.4 on 2022-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0022_alter_register_pic_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo2.png', upload_to='Profile Pic'),
        ),
    ]
