# Generated by Django 4.0.2 on 2022-04-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0027_alter_register_pic_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo10.png', upload_to='Profile Pic'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
