# Generated by Django 4.0.2 on 2022-04-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0030_book_alter_register_pic_delete_checkout_book_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
