# Generated by Django 4.0.2 on 2022-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0031_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo3.jpg', upload_to='Profile Pic'),
        ),
    ]
