# Generated by Django 4.0.2 on 2022-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesapp', '0033_alter_register_pic_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo4.png', upload_to='Profile Pic'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
